{% set version = "0.2.1" %}

package:
  name: locket
  version: {{ version }}

source:
  fn: locket-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/l/locket/locket-{{ version }}.tar.gz
  md5: b5e4e9dea58264f636f7044c867e2c6d

build:
  number: 1
  script: python setup.py install

requirements:
  host:
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - locket

about:
  home: https://github.com/mwilliamson/locket.py
  license: BSD 2-Clause
  license_file: LICENSE
  summary: File-based locks for Python for Linux and Windows
  description: |
    Locket implements a lock that can be used by multiple processes provided
    they use the same path.
  doc_url: https://pypi.python.org/pypi/locket
  doc_source_url: https://github.com/mwilliamson/locket.py/blob/master/README.rst
  dev_url: https://github.com/mwilliamson/locket.py

extra:
  recipe-maintainers:
    - jcrist
